-- MySQL Script generated by MySQL Workbench
-- Sat Feb 13 13:50:29 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema avaliabrasil_dev
-- -----------------------------------------------------
-- Development version of Avalia Brasil mysqldb.
DROP SCHEMA IF EXISTS `avaliabrasil_dev` ;

-- -----------------------------------------------------
-- Schema avaliabrasil_dev
--
-- Development version of Avalia Brasil mysqldb.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avaliabrasil_dev` DEFAULT CHARACTER SET utf8 ;
USE `avaliabrasil_dev` ;

-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`category` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) UNSIGNED ZEROFILL NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`place_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`place_type` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`place_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_category` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `idcategoria_idx` (`id_category` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `idcategoria-tipoinst`
    FOREIGN KEY (`id_category`)
    REFERENCES `avaliabrasil_dev`.`category` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`user` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` INT NOT NULL DEFAULT '0',
  `usertype` INT NOT NULL DEFAULT '0',
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusuario_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`region` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_ibge` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`state` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_region` INT NOT NULL,
  `id_ibge` VARCHAR(45) NULL,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uf` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idregiao_idx` (`id_region` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `idregiao-est`
    FOREIGN KEY (`id_region`)
    REFERENCES `avaliabrasil_dev`.`region` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`city` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `id_state` INT NOT NULL,
  `id_ibge` VARCHAR(45) NULL,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idmunicipio_UNIQUE` (`id` ASC),
  INDEX `idestado_idx` (`id_state` ASC),
  CONSTRAINT `idestado-muni`
    FOREIGN KEY (`id_state`)
    REFERENCES `avaliabrasil_dev`.`state` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`place` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`place` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_type` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `id_city` INT NOT NULL,
  `place_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idinstituicao_UNIQUE` (`id` ASC),
  INDEX `idtipoinstituicao_idx` (`id_type` ASC),
  INDEX `idmunicipio_idx` (`id_city` ASC),
  UNIQUE INDEX `place_id_UNIQUE` (`place_id` ASC),
  CONSTRAINT `idtipoinstituicao`
    FOREIGN KEY (`id_type`)
    REFERENCES `avaliabrasil_dev`.`place_type` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idmunicipio-inst`
    FOREIGN KEY (`id_city`)
    REFERENCES `avaliabrasil_dev`.`city` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`masterinstrument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`masterinstrument` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`masterinstrument` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idinstrumento-master_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`instrument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`instrument` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`instrument` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `id_masterinstrument` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idinstrumento-master_idx` (`id_masterinstrument` ASC),
  UNIQUE INDEX `idinstrumento_UNIQUE` (`id` ASC),
  CONSTRAINT `idinstrumento-master-instr`
    FOREIGN KEY (`id_masterinstrument`)
    REFERENCES `avaliabrasil_dev`.`masterinstrument` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`evaluation` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`evaluation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_user` INT NOT NULL,
  `id_place` INT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `id_instrument` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idavaliacao_UNIQUE` (`id` ASC),
  INDEX `idusuario_idx` (`id_user` ASC),
  INDEX `idinstituicao_idx` (`id_place` ASC),
  INDEX `idinstrumento_idx` (`id_instrument` ASC),
  CONSTRAINT `idusuario-ava`
    FOREIGN KEY (`id_user`)
    REFERENCES `avaliabrasil_dev`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idinstituicao-ava`
    FOREIGN KEY (`id_place`)
    REFERENCES `avaliabrasil_dev`.`place` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idinstrumento-ava`
    FOREIGN KEY (`id_instrument`)
    REFERENCES `avaliabrasil_dev`.`instrument` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`masterdimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`masterdimension` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`masterdimension` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `id_masterinstrument` INT NOT NULL,
  `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idinstrumento-master_idx` (`id_masterinstrument` ASC),
  CONSTRAINT `idinstrumento-master-dim`
    FOREIGN KEY (`id_masterinstrument`)
    REFERENCES `avaliabrasil_dev`.`masterinstrument` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`question_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`question_type` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`question_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `is_likert` TINYINT(1) NOT NULL,
  `is_numeric` TINYINT(1) NOT NULL,
  `is_comment` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtipopergunta_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`item` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_masterdimension` INT NOT NULL,
  `id_instrument` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `order` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `iddimensao-master_idx` (`id_masterdimension` ASC),
  INDEX `idinstrumento_idx` (`id_instrument` ASC),
  UNIQUE INDEX `iditem_UNIQUE` (`id` ASC),
  CONSTRAINT `iddimensao-master-item`
    FOREIGN KEY (`id_masterdimension`)
    REFERENCES `avaliabrasil_dev`.`masterdimension` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idinstrumento-item`
    FOREIGN KEY (`id_instrument`)
    REFERENCES `avaliabrasil_dev`.`instrument` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`question` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `id_type` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `id_item` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idpergunta_UNIQUE` (`id` ASC),
  INDEX `idtipopergunta_idx` (`id_type` ASC),
  INDEX `iditem-perg_idx` (`id_item` ASC),
  CONSTRAINT `idtipopergunta-perg`
    FOREIGN KEY (`id_type`)
    REFERENCES `avaliabrasil_dev`.`question_type` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `iditem-perg`
    FOREIGN KEY (`id_item`)
    REFERENCES `avaliabrasil_dev`.`item` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`answer_likert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`answer_likert` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`answer_likert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_evaluation` INT NOT NULL,
  `id_question` INT NOT NULL,
  `answer` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idresposta_UNIQUE` (`id` ASC),
  INDEX `idavaliacao_idx` (`id_evaluation` ASC),
  INDEX `idpergunta_idx` (`id_question` ASC),
  CONSTRAINT `idavaliacao-resp`
    FOREIGN KEY (`id_evaluation`)
    REFERENCES `avaliabrasil_dev`.`evaluation` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idpergunta-resp`
    FOREIGN KEY (`id_question`)
    REFERENCES `avaliabrasil_dev`.`question` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`answer_text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`answer_text` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`answer_text` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_evaluation` INT NOT NULL,
  `id_question` INT NOT NULL,
  `answer` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idresposta_UNIQUE` (`id` ASC),
  INDEX `idavaliacao_idx` (`id_evaluation` ASC),
  INDEX `idpergunta_idx` (`id_question` ASC),
  CONSTRAINT `idavaliacao-resp0`
    FOREIGN KEY (`id_evaluation`)
    REFERENCES `avaliabrasil_dev`.`evaluation` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idpergunta-resp0`
    FOREIGN KEY (`id_question`)
    REFERENCES `avaliabrasil_dev`.`question` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avaliabrasil_dev`.`answer_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `avaliabrasil_dev`.`answer_number` ;

CREATE TABLE IF NOT EXISTS `avaliabrasil_dev`.`answer_number` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_evaluation` INT NOT NULL,
  `id_question` INT NOT NULL,
  `answer` DECIMAL NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idresposta_UNIQUE` (`id` ASC),
  INDEX `idavaliacao_idx` (`id_evaluation` ASC),
  INDEX `idpergunta_idx` (`id_question` ASC),
  CONSTRAINT `idavaliacao-resp1`
    FOREIGN KEY (`id_evaluation`)
    REFERENCES `avaliabrasil_dev`.`evaluation` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idpergunta-resp1`
    FOREIGN KEY (`id_question`)
    REFERENCES `avaliabrasil_dev`.`question` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO user1;
 DROP USER user1;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
